# Spring
server.port=8060
logger.show_sql=true
spring.http.multipart.max-file-size=200MB
spring.http.multipart.max-request-size=500MB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB

# Engine
engine.run.mode=SINGLE
engine.store.meta.mode=CLOUD
engine.model2ddl.mode=CREATE

# Hazelcast
hazelcast.mode.cs.enabled=false
hazelcast.mode.cs.address=hazelcast:5701
hazelcast.cluster-name=hazelcast-cluster
hazelcast.network.join.auto-detection.enabled=false
hazelcast.network.join.multicast.enabled=false
hazelcast.network.join.kubernetes.enabled=false
hazelcast.network.join.kubernetes.namespace=default
hazelcast.map.hazelcast-map.backup-count=0
hazelcast.managementCenter.console.enabled=false
hazelcast.managementCenter.scripting.enabled=false

# App auth placeholder for local compose deployment.
appAuth.Server=http://iidp-app:8060
appAuth.registerUrl=/api/v1/register
appAuth.unregisterUrl=/api/v1/unregister
appAuth.authUrl=/api/v1/auth
appAuth.engineVersion=v1.0.0

# MinIO
minio.endpoint=http://minio:9000
minio.accessKey=snest
minio.secretKey=12345678
minio.bucketName=apps

# Redis
redis.host=redis
redis.port=6379
redis.db=0
redis.password=redis
redis.max_total=100
redis.max_idle=100
redis.min_idle=0
redis.max_wait_millis=1000
redis.connection_timeout=2000
redis.so_timeout=30000

getModel.whiteList=*.rbac login log,*.meta tree_data
kkfile.host=http://host.docker.internal:8012
server.host=http://localhost:8060
