########DBCP##########
driverClassName=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://mysql:3306/iidp_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
username=iidp
password=iidp123456
initialSize=5
maxActive=30
minIdle=5
maxWait=6000
filters=stat
timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=300000
testOnBorrow=false
testOnReturn=false
testWhileIdle=true
poolPreparedStatements=true
maxOpenPreparedStatements=20
