#spring.mvc.pathmatch.matching-strategy=ant_path_matcher
logging:
config: logback.xml
level:
com.sie.snest: info

#spring
server.port=8060
logger.show_sql=true
spring.http.multipart.max-file-size=200MB
spring.http.multipart.max-request-size=500MB
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB

#profile
engine.store.meta.mode=CLOUD
#engine.run.mode=DISTRIBUTED_V2
engine.run.mode=single

iidp.model.facade.access.throw.exp=false
iidp.app.service.whitelist.GET_ACCESS_AUTH=none


# Hazelcast \u914D\u7F6E
hazelcast.mode.cs.enabled = false
hazelcast.mode.cs.address = "hazelcast:5701"
hazelcast.cluster-name = hazelcast-cluster
hazelcast.network.join.auto-detection.enabled = false
hazelcast.network.join.multicast.enabled = false
hazelcast.network.join.kubernetes.enabled = false
hazelcast.network.join.kubernetes.namespace = default
hazelcast.map.hazelcast-map.backup-count = 0
hazelcast.managementCenter.console.enabled = false
hazelcast.managementCenter.scripting.enabled = false

appAuth.Server=http://192.168.168.176:8081
appAuth.registerUrl=/api/v1/register
appAuth.unregisterUrl=/api/v1/unregister
appAuth.authUrl=/api/v1/auth
appAuth.engineVersion=v1.0.0

#NONE: \u8DF3\u8FC7\u6570\u636E\u5E93\u66F4\u65B0
#CREATE: \u66F4\u65B0\u6570\u636E\u5E93\u8868\u3002\u7F3A\u7701\u503C
#VALIDATE: \u4E0D\u66F4\u65B0\u6570\u636E\u5E93\uFF0C\u4F46\u662F\u4F1A\u5728\u63A7\u5236\u5408\u6253\u5370\u66F4\u65B0\u8BED\u53E5\uFF0C\u901A\u5E38\u7528\u4E8E\u9879\u76EE\u4E0A\u7EBF\u540E
#engine.model2ddl.mode=CREATE
#seeder.sync=false

#minio
minio.endpoint=http://192.168.175.54:9000
minio.accessKey=snest
minio.secretKey=12345678
minio.bucketName=apps

redis.host=192.168.175.198
redis.port=6379
redis.db=9
redis.password=aY4v4g3B
redis.max_total=100
redis.max_idle=100
redis.min_idle=0
redis.max_wait_millis=1000
redis.connection_timeout=2000
redis.so_timeout=30000


#cas\u5355\u70B9\u767B\u5F55 \u5C0F\u718Auat\u73AF\u5883\u914D\u7F6E
cas.serverUrlPrefix = https://idmtest.bears.com.cn:8002
cas.serverLoginUrl = https://idmtest.bears.com.cn:8002/login
cas.serverLogoutUrl = https://idmtest.bears.com.cn:8002/logout
cas.clientHostUrl = https://srmuat.bears.com.cn/api/
cas.frontLoginUrl = https://srmuat.bears.com.cn/api/
cas.urlPatterns = /loginCas
cas.frontHomeUrl = https://srmuat.bears.com.cn/iidp/base/base_overview_menu

getModel.whiteList=*.rbac login log,*.meta tree_data

# kkfile\u57DF\u540D
kkfile.host = http://192.168.175.42:30846

# \u57DF\u540D
server.host = http://10.10.4.14:8061